# Generated by Django 5.2.14 on 2026-05-10 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('accommodation', 'Accommodation'), ('transportation', 'Transportation'), ('food', 'Food & Dining'), ('activities', 'Activities & Tours'), ('shopping', 'Shopping'), ('insurance', 'Insurance'), ('visa', 'Visa & Documents'), ('miscellaneous', 'Miscellaneous')], max_length=30)),
                ('planned', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('color', models.CharField(default='#14b8a6', max_length=7)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_categories', to='trips.trip')),
            ],
            options={
                'ordering': ['category'],
                'unique_together': {('trip', 'category')},
            },
        ),
        migrations.CreateModel(
            name='BudgetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='budget.budgetcategory')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
