# Generated by Django 5.2.14 on 2026-05-10 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('clothing', 'Clothing'), ('toiletries', 'Toiletries'), ('electronics', 'Electronics'), ('documents', 'Documents'), ('essentials', 'Essentials'), ('miscellaneous', 'Miscellaneous')], default='essentials', max_length=20)),
                ('is_packed', models.BooleanField(default=False)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packing_items', to='trips.trip')),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
    ]
